### ISSUE TITLE
auto upgrade yt-dlp at container start ?

### ISSUE THREAD

**Issue by typhoe** [BananaPukeh/plex-music-grabber#6]
Hi,

would it be possible to run once at container start a ```pip install --upgrade -r requirements.txt``` to get yt-dlp updated to the latest ?

Youtube often makes little changes that blocks direct downloads...

The latest docker container you published is based on yt-dlp 2022.11.11 and right now yt-dlp version is 2023.03.04

Thank you!

**Comment by BananaPukeh** [comment]
Nice idea! Noticed this myself a while ago. I was thinking about monthly/weekly automated releases installing the latest packages. But this might be a better idea. I’ll take a look what I can do

**Comment by typhoe** [comment]
Thank you very much!

For now, I simply built the container from scratch using the Dockerfile and src you provided on this repo and as the pip install requirement is in the Dockerfile, I got a perfectly up to date container.
Using the one from dockerhub, yt-dlp version was too old and I got an error (that is already corrected in latest yt-dlp packages), that's why I was looking for a way to get it updated ;-)

May I also suggest the ability to set interval by library/path ?
All my libraries don't get new items as often as others. And some library are more like "archive libraries" than others and thus could live with a scan once a week instead of every 5mn
If you think it would be a good idea, I can create an other issue for that too

**Comment by BananaPukeh** [comment]
@typhoe So automated deployments are implemented. Every Sunday evening, a new image will be built and pushed with the `latest` tag and build date tag. I just have to validate that the schedule actually runs.

Might consider doing this on a daily basis, but seems a bit of overkill. Time will tell, iguess.

Regarding your other idea, seems like a neat feature, you may create an issue for that if you like.
However, do you actually run a full library scan every 5 minutes? Seems a bit overkill, I have mine configured at `86400` seconds =(24h). I don't think 5-minute runs will benefit you, since Plex also needs to update all metadata, which I believe is also done using a scheduled Plex job.

**Comment by typhoe** [comment]
My bad, I don't even know how I mistake your default setting 3600 (that I didn't change and I'm using) with 300s = 5mn...
And yes, no point running the scan so often!

Nice for the update schedule of the container, I'll switch back to the dockerhub then!
Thank you!

And I'll create another issue for the new suggestion
